#Site settings
title: Cardiff Math Code Club
url: "http://CardiffMathematicsCodeClub.github.io"
version: 3.5.238

markdown: kramdown
highlighter: pygments

paginate: 10
paginate_path: "/blog/page:num"

encoding: utf-8
description: Cardiff University School of Mathematics Code Club website
keywords: cardiff,university,uni,maths,math,mathematics,code,club,website,python,java,pascal,vb,elbow,atom,vim,sublime

gems:
    - jekyll-gist
    - jekyll-paginate
    - pygments

collections:
  workshops:
    output: true
